name: EpicaCore
version: '${project.version}'
main: org.nilscoy.epicacore.EpicaCore
api-version: '1.20'
authors: [NilsCoy]
description: Created for Epica
depend:
  - NBTAPI
  - PlaceholderAPI
commands:
  core: {}
