name: EpicaCore
version: '1.0-SNAPSHOT'
main: org.nilscoy.epicacore.EpicaCore
api-version: '1.20'
authors: [NilsCoy]
description: Created for Epica
softdepend:
  - PlaceholderAPI
commands:
  core: {}
